services:
    allhands22:
        image: "${TESTING_IMAGE}"
        
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./healthchecks:/healthchecks
        healthchecks:
            test: /healthchecks/postgres-healthchecks
            interval: "5s"
    sut:
        image: "${TESTING_IMAGE}"
        depends_on:
            allhands22:
                condition: service_started
            postgres:
                condition: service_healthy
        command: curl --fail http://allhands22:80 || exit 1